apiVersion: apps/v1
kind: Deployment
metadata:
  name: forecastapp
  labels:
    app: forecastapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: forecastapp
  template:
    metadata:
      labels:
        app: forecastapp
    spec:
      containers:
      - image: kupidun/my_flask_app:latest
        name: forecastapp
        ports:
        - containerPort: 5000

